steps:
    -   id: GAR auth
        name: node:20
        entrypoint: /bin/sh
        args:
            - -c
            - npx google-artifactregistry-auth

    -   id: install
        name: node:20
        entrypoint: yarn
        args:
            - install

    -   id: lint
        name: node:20
        entrypoint: yarn
        args:
            - lint-ci --target=^(master|develop)$

    -   id: test
        name: node:20
        entrypoint: yarn
        args:
            - test
    
    -   id: build
        name: node:20
        entrypoint: yarn
        args:
            - build
