availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/github-access-token/versions/latest
          env: GITHUB_ACCESS_TOKEN
        - versionName: projects/${PROJECT_ID}/secrets/datadog-api-key/versions/latest
          env: DATADOG_API_KEY

steps:
    -   id: GAR auth
        name: node:20
        entrypoint: /bin/sh
        args:
            - -c
            - npx google-artifactregistry-auth

    -   id: install
        name: node:20
        entrypoint: yarn
        args:
            - install

    -   id: release
        name: node:20
        entrypoint: /bin/sh
        args:
            - -c
            - |-
              git init
              git remote set-url origin https://$$GITHUB_ACCESS_TOKEN@github.com/ubitransports/ier-server.git
              git config --unset credential.helper
              git config user.name "Cloud Build Runner"
              git config user.email "ubi-eng-devops@ubitransport.com"
              git fetch --unshallow
              git checkout $BRANCH_NAME
              GITHUB_TOKEN=$$GITHUB_ACCESS_TOKEN DATADOG_API_KEY=$$DATADOG_API_KEY yarn run release
        env:
          - CI=true
          - DEBUG=true
          - DATADOG_SITE=datadoghq.eu
          - DATADOG_API_HOST=api.datadoghq.eu
        secretEnv:
            - 'GITHUB_ACCESS_TOKEN'
            - 'DATADOG_API_KEY'
